#!/bin/sh
# Run a command in the app's development environment.

set -e

[ -f /etc/inside-container ] && exec "$@"

appdir=$(cd $(dirname "$0")/.. && pwd)
imagename="${PWD##*/}_web"

cmd="$@"; [ "$#" -eq 0 ] && cmd=bash
image=${DOCKER_IMAGE:=$imagename}

if [ ! -f script/.env ]; then
    echo "Environment variables file (script/.env) not found!"
    exec docker run -i -t -v "$appdir:/app" $image $cmd
else
    exec docker run --env-file="script/.env" -i -t -v "$appdir:/app" $image $cmd
fi
