#!/bin/sh

set -e

appdir=$(cd $(dirname "$0")/.. && pwd)
[ -f /etc/inside-container  ] || exec "$appdir/script/app-env" $0 $@

export PYTHONPATH="${appdir}/src:$PYTHONPATH"

pytest -v --durations=5 tests
